#!/usr/bin/ruby -w

$:.push(File.dirname(__FILE__))
require 'config'
require 'net/smtp'

config = Clif::Config.new(File.join(ENV['HOME'], '.stac', 'config'))['wifi-password']

$base_oid = "1.3.6.1.4.1.9.6.1.104.1.5.1.1.14"
$virtual_access_points = {
  'Office' => 5,
  'Public' => 6,
  'Presenters' => 7,
}

def usage
  $stderr.puts "usage: #{$0} <access point name> [<new password>]"
  exit 1
end

if ARGV.length < 1 || ARGV.length > 2
  usage()
end

access_point_name = ARGV.shift
if !$virtual_access_points[access_point_name]
  $stderr.puts "ERROR: cannot find access point named '#{access_point_name}'; options are #{$virtual_access_points.keys.sort.join(', ')}."
  usage()
end

oid = "#{$base_oid}.#{$virtual_access_points[access_point_name]}"

new_password = ARGV.shift

if new_password
  config['agents'].each do |agent|
    print "#{agent}: "
    system 'snmpset', '-v2c', '-c', config['community'], agent, oid, 's', new_password
  end
  recipients = config['notification']
  message = <<EOT
From: St Andrew's Centre Wi-Fi Robot <stac@meliorist.co.uk>
To: #{recipients.join(', ')}
Subject: Wi-Fi Password Update for St Andrew's #{access_point_name}

This is a notification that the Wi-Fi password for the St Andrew's
#{access_point_name} network has been updated.

New password: #{new_password}
EOT

  Net::SMTP.start('localhost', nil, `hostname -f`.chomp) do |smtp|
    smtp.send_message message, 'stac@meliorist.co.uk', *recipients
  end

else
  config['agents'].each do |agent|
    print "#{agent}: "
    system 'snmpget', '-v2c', '-c', config['community'], agent, oid
  end
end
